### ISSUE TITLE
FNA++ code

### ISSUE THREAD

**Issue by Hrayo712** [JaminFong/FNA#11]
Hello! Thanks for the great contribution, keep up the good work!

I was wondering if there is any estimation for when the FNA++ code will be available

**Comment by JaminFong** [comment]
Hi! Thanks for your attention. We plan to release the FNA++ code after the paper is on publication. Please pay attention to subsequent updates if needed.

**Comment by Hrayo712** [comment]
Hi @JaminFong 

Any updates on when FNA++ might become available ? Any estimation :) ?

**Comment by JaminFong** [comment]
Hi, I'm sorry as I'm occupied with other things recently. There is not a specific timeline for releasing the new code yet, but the implementation is not hard. You could have a try with it, and please ask if any questions.

**Comment by hohohoho1111** [comment]
Hello! thanks for your good work! 
I was wondering if when the FNA++'s parameter remapping func code will be available...
I don't know..how can I implement for "expanding width/reducing kernel size"  in parameter remapping
Could I know that....? 😭😭😭 @JaminFong
