### ISSUE TITLE
Questions about the Search Space and inference time

### ISSUE THREAD

**Issue by Hrayo712** [JaminFong/FNA#12]
Hi! thanks again for the contribution!

I have a question: In the paper you mention that the search space is within the Backbone, and during the experimentation, you couple FNA with RetinaNet. 

However, RetinaNet is a Network with a Backbone + a feature pyramid neck (FPN) + head. 

This means that FNA's search space does not cover the Feature pyramid neck, right ?
I.e., FNA(RetinaNet)  => FNA+ FPN + RetinaNet head 

Also, do you have numbers on inference time ?

I hope you can clarify this. Thanks a lot 👍

**Comment by JaminFong** [comment]
Yeah, you are right. FNA searches for the backbone network and the head part is not changed yet. However, if you have a plan to search for the head architecture along with the backbone, with FNA equipped, the search can also be performed easily with a low computation cost.
We aim at optimizing FLOPs in the experiments and do not provide inference time measurement. In addition, you may make a lookup table of latency if you wanna optimize the inference time of the network.
Hoping this could resolve your questions.
