### ISSUE TITLE
Error when performing architecture adaptation in non distributed mode

### ISSUE THREAD

**Issue by Hrayo712** [JaminFong/FNA#14]
Hello!

I am trying to run the architecture adaptation with a single GPU for RetinaNet. For this, I simply run the script without the 
`torch.distributed.launch --nproc_per_node=8` and set `--launcher none`. 

The process runs smoothly for 8 epochs in training mode, as expected. However, once the first iteration in architecture mode runs, and the `ArchOptimizerHook.after_train_iter` is executed, I am getting an error within the `rescale_arch_params function` signaling that there is no `model.alpha_head_index` parameter within the model. 

I noticed this `rescale_arch_params ` function call is commented out for the Distributed execution of the architecture adaptation, in `ArchDistOptimizerHook.after_train_iter`. So, I commented it out, and the process is now running smoothly again. 

**My question is then:** is it correct to simply comment this out ? is there another consideration that I should take to perform the architecture adaptation in a single GPU (non distributed) ?

I hope you can comment on this, thanks in advance for your time!

**Comment by JaminFong** [comment]
Hi, please still use the distributed mode even with only one GPU. The non-distributed mode is deprecated. Please refer to https://github.com/JaminFong/FNA/issues/13 .

**Comment by Hrayo712** [comment]
Ok. I'll simply launch the script with --nnproc_per_node=1 then. Thanks!
