### ISSUE TITLE
Does the code include the search?

### ISSUE THREAD

**Issue by betterhalfwzm** [JaminFong/FNA#2]
Does the code include the search? And run param_adapt.sh search and finetune?  Thx!!!!

**Comment by JaminFong** [comment]
Hi, the code for search (architecture adaptation) will be released later after we clean it up. Please pay attention to the update of the repo.

**Comment by betterhalfwzm** [comment]
> Hi, the code for search (architecture adaptation) will be released later after we clean it up. Please pay attention to the update of the repo.

Thank you for your quick reply. I'm very interested in your work，Looking forward to your update as soon as possible.

**Comment by lxtGH** [comment]
Hi! Do you have specific timeline on release search code? @JaminFong

**Comment by JaminFong** [comment]
Hi! The search code of detection is released including RetinaNet and SSDLite.

**Comment by cwhuang888** [comment]
Hi, will you also release search code for segmentation?
Thanks!!

**Comment by Hrayo712** [comment]
Hi, is it still the intention to release the search code for segmentation ?

**Comment by JaminFong** [comment]
@Hrayo712 Hi! The search code for segmentation is planned to be released along with the FNA++ code after the FNA++ paper is on publication. Thanks for your attention!
