### ISSUE TITLE
Passing information from arch_adapt_ssdlite to param_adapt_ssdlite

### ISSUE THREAD

**Issue by soyebn** [JaminFong/FNA#3]
Came across your wonderful and very useful work. I am trying to recreate results you have published  before customizing network further. I had few questions.   

1. Does the architecture (Ni) found while running arch_adapt_ssd_lite.sh get printed in the .log file ?
And does one need to manually copy that architecture info from .log file to fna_ssdlite_retrain.py as _net_config_ before running param_adapt_ssdlite.sh?

2. Btw, I got very different searched architecture (Ni) when I ran arch_adapt_ssdlite.sh. I am running on 2 GTX1080Ti. Could that play big role?
Is there a way to find out whether architecture search was successful or not before one embarks on training journey which takes relatively longer time. 

Thanks for your help.

**Comment by JaminFong** [comment]
Hi, thanks for your attention to our work.
1. The searched architecture is printed in the .log file. And you need to manually copy the net_config to the config file of the latter parameter adaptation, e.g., https://github.com/JaminFong/FNA/blob/08bbc2c9fb69dcdaeac90f0a48a723f7ebf2fd46/fna_det/configs/fna_ssdlite_retrain.py#L14
2. We suggest running the code on 8 GPUs to keep the total batch size the same as ours, as the small batch size may lead to performance degradation.
Retraining the searched architecture might be the best way to validate the performance. You could also observe the searched architecture by the logged net_config.
Hope my answer could help you!

**Comment by soyebn** [comment]
I searched and retrained with retinanet with 4x1080TI GPUs and got 32.9 mAP, very close to your reported. Thanks for your help.
