### ISSUE TITLE
died with <Signals.SIGILL: 4>

### ISSUE THREAD

**Issue by Harvest-Li** [JaminFong/FNA#4]
Hi, 
When I tried running the command `sh scripts/arch_adapt_retinanet.sh` with the model seed_mbv2.pt you provided as mentioned in README.md, I got following error, 
`06/26 06:47:57 PM - Start loading the model from ./seed_mbv2.pt
06/26 06:47:57 PM - Remapping for architecture adaptation starts!
06/26 06:47:57 PM - Remapping for architecture adaptation finished!
Traceback (most recent call last):
  File "/home/liqs/anaconda3/envs/py37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/liqs/anaconda3/envs/py37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/liqs/anaconda3/envs/py37/lib/python3.7/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/home/liqs/anaconda3/envs/py37/lib/python3.7/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/home/liqs/anaconda3/envs/py37/bin/python', '-u', './tools/search.py', '--local_rank=0', './configs/fna_retinanet_fpn_search.py', '--launcher', 'pytorch', '--seed', '1', '--work_dir', './', '--data_path', './coco/']' died with <Signals.SIGILL: 4>.`

can you help me to fix it?

**Environment:**
- OS: CentOS Linux release 7.4.1708
- GPU: P100
- Drivers: nvidia-418.43
- cuda 10.0.130
- cudnn  7.6.5
- Python: 3.7.7
- Pytorch: 1.1.0
- mmdet 0.6.0
- mmcv 0.2.10

Thanks!

**Comment by Harvest-Li** [comment]
```
06/26 06:47:57 PM - Start loading the model from ./seed_mbv2.pt
06/26 06:47:57 PM - Remapping for architecture adaptation starts!
06/26 06:47:57 PM - Remapping for architecture adaptation finished!
Traceback (most recent call last):
  File "/home/liqs/anaconda3/envs/py37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/liqs/anaconda3/envs/py37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/liqs/anaconda3/envs/py37/lib/python3.7/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/home/liqs/anaconda3/envs/py37/lib/python3.7/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/home/liqs/anaconda3/envs/py37/bin/python', '-u', './tools/search.py', '--local_rank=0', './configs/fna_retinanet_fpn_search.py', '--launcher', 'pytorch', '--seed', '1', '--work_dir', './', '--data_path', './coco/']' died with <Signals.SIGILL: 4>.
```

**Comment by JaminFong** [comment]
It seems that the setup of the script is not so correct. It should be started by `python -m torch.distributed.launch --nproc_per_node=8 ./tools/search.py ...` to launch the distributed mode not `python -u ./tools/search.py` provided by your log.

**Comment by Harvest-Li** [comment]
I haven't modified the command in  scripts/arch_adapt_retinanet.sh your provided:
```
# !/usr/bin/env sh

python -m torch.distributed.launch --nproc_per_node=8 ./tools/search.py \
            ./configs/fna_retinanet_fpn_search.py \
            --launcher pytorch \
            --seed 1 \
            --work_dir ./ \
            --data_path ./coco/
```

I don't know why this is happening after running `sh scripts/arch_adapt_retinanet.sh`

**Comment by JaminFong** [comment]
Could you please check if mmdetection is compiled successfully by running any script of the original mmdetection?

**Comment by Harvest-Li** [comment]
Very helpful! It should be a failed compilation of mmdetection. I replace gcc-4.8 that i originally used with gcc-5.5, and rebuild the environment this project needs and it works. Thank you for your help!

**Comment by Amri95** [comment]
> Hi,
> When I tried running the command `sh scripts/arch_adapt_retinanet.sh` with the model seed_mbv2.pt you provided as mentioned in README.md, I got following error,
> `06/26 06:47:57 PM - Start loading the model from ./seed_mbv2.pt 06/26 06:47:57 PM - Remapping for architecture adaptation starts! 06/26 06:47:57 PM - Remapping for architecture adaptation finished! Traceback (most recent call last): File "/home/liqs/anaconda3/envs/py37/lib/python3.7/runpy.py", line 193, in _run_module_as_main "__main__", mod_spec) File "/home/liqs/anaconda3/envs/py37/lib/python3.7/runpy.py", line 85, in _run_code exec(code, run_globals) File "/home/liqs/anaconda3/envs/py37/lib/python3.7/site-packages/torch/distributed/launch.py", line 235, in <module> main() File "/home/liqs/anaconda3/envs/py37/lib/python3.7/site-packages/torch/distributed/launch.py", line 231, in main cmd=process.args) subprocess.CalledProcessError: Command '['/home/liqs/anaconda3/envs/py37/bin/python', '-u', './tools/search.py', '--local_rank=0', './configs/fna_retinanet_fpn_search.py', '--launcher', 'pytorch', '--seed', '1', '--work_dir', './', '--data_path', './coco/']' died with <Signals.SIGILL: 4>.`
> 
> can you help me to fix it?
> 
> **Environment:**
> 
> * OS: CentOS Linux release 7.4.1708
> * GPU: P100
> * Drivers: nvidia-418.43
> * cuda 10.0.130
> * cudnn  7.6.5
> * Python: 3.7.7
> * Pytorch: 1.1.0
> * mmdet 0.6.0
> * mmcv 0.2.10
> 
> Thanks!

Hi there, 
My environment is the same as yours but created using anaconda in Ubuntu 18.04. I have pasted a snap of the errors I am getting, please suggest the solution if possible. Thank you! Best regards.
![fn](https://user-images.githubusercontent.com/37174642/116990759-89530980-ad0e-11eb-82a3-2f3918841d74.jpg)
