### ISSUE TITLE
OSError: ./seed_mbv2.pt is not a checkpoint file

### ISSUE THREAD

**Issue by LianShuaiLong** [JaminFong/FNA#6]
您好，我在搭好FNA算法的环境后，直接运行fnadet的代码的时候，出现了上述错误，我查了一下，repo里面并没有mobilenetv2的预训练模型参数，请问自行下载预训练的权重放到对应位置就可以了么？

**Comment by JaminFong** [comment]
您好，是的，烦请自行下载ReadMe中给出的MobileNetV2预训练模型并放到对应位置。

**Comment by LianShuaiLong** [comment]
> 您好，是的，烦请自行下载ReadMe中给出的MobileNetV2预训练模型并放到对应位置。

咦，我放到对应位置后，仍然提示OSError: ./seed_mbv2.pt is not a checkpoint file
这个是怎么回事呀？

**Comment by JaminFong** [comment]
您好，您的路径是否一致呢？

**Comment by LianShuaiLong** [comment]
> 您好，您的路径是否一致呢？

您好，我把seed_mbv2.pt放在了路径tools/下面
<img width="496" alt="5CC02E20-B76C-4c74-A081-7238FBEDFBF2" src="https://user-images.githubusercontent.com/23699530/91976833-2c085200-ed54-11ea-8c0c-25df7a05196c.png">
model的loadpath设置的是./seed_mbv2.pt
另外我自己写了个脚本判断seed_mbv2.pt是不是文件，脚本返回结果是True,但是在您的项目里面的utils.py返回的是False

**Comment by JaminFong** [comment]
您的`loadpath`设置的当前路径`./`，但是放在了`./tools/`下，这是不一致的。

**Comment by LianShuaiLong** [comment]
> 您的`loadpath`设置的当前路径`./`，但是放在了`./tools/`下，这是不一致的。
哈哈哈，好的，我脑子秀逗了，我直接吧loadpath里面设置成了绝对路径了，现在解决了，谢谢您

**Comment by JaminFong** [comment]
My pleasure! Feel easy to reopen it if any questions.
