### ISSUE TITLE
 died with <Signals.SIGSEGV: 11>

### ISSUE THREAD

**Issue by LianShuaiLong** [JaminFong/FNA#7]
嗨，有两个问题请教一下：
(1)当我运行sh scripts/arch_adapt_ssdlite.sh 的时候遇到了 died with <Signals.SIGSEGV: 11>的错误,下面的是我自己的环境：
>>> print(torch.__version__)
1.3.0
>>> print(mmcv.__version__)
0.2.10
>>> print(mmdet.__version__)
0.6.0+53c647e
gcc version 5.5.0 20171010 (Ubuntu 5.5.0-12ubuntu1~16.04)
>>> print(torch.version.cuda)
10.1.243
>>> print(torch.backends.cudnn.version())
7603
(2)我是想利用AUTODL去做分类的问题，我的初步想法是跑通FNA之后，然后把backbone提取出来然后做分类，但是我看了一下FNA代码，里面有大量的mmdetection相关的部分改起来难度有些大，是不是相较于FNA算法我更应该采用DenseNAS，

**Comment by JaminFong** [comment]
(1) 您可以跑一下该版本mmdet自带的script以验证mmdet是否成功编译
(2) 感谢您对我们方法的兴趣，FNA也可以用到分类任务上，DenseNAS在搜索空间上具有更高的灵活度，您可以根据自己的需求进行尝试

**Comment by LianShuaiLong** [comment]
> (1) 您可以跑一下该版本mmdet自带的script以验证mmdet是否成功编译
> (2) 感谢您对我们方法的兴趣，FNA也可以用到分类任务上，DenseNAS在搜索空间上具有更高的灵活度，您可以根据自己的需求进行尝试

好的，我有重新配置了一下环境，已经好了，原因应该是不能采用pip的方式安装mmcv包，
