### ISSUE TITLE
关于bbox_head

### ISSUE THREAD

**Issue by LianShuaiLong** [JaminFong/FNA#8]
![image](https://user-images.githubusercontent.com/23699530/92554116-2b614580-f297-11ea-8558-3f6e94f2306d.png)
您好，我在阅读FNA的代码的时候，没有找到使用bbox_head部分的代码，麻烦问一下这部分是在哪里调用的？

**Comment by JaminFong** [comment]
https://github.com/JaminFong/FNA/blob/898ec5d3f24c3128cf1a4bb276a542f1fab3bad5/fna_det/models/ssdlite_head.py#L13
mmdet通过注册机制调用model

**Comment by LianShuaiLong** [comment]
> https://github.com/JaminFong/FNA/blob/898ec5d3f24c3128cf1a4bb276a542f1fab3bad5/fna_det/models/ssdlite_head.py#L13
> 
> 
> mmdet通过注册机制调用model

好的，感谢！
